### ISSUE TITLE
Riak 2.0?

### ISSUE THREAD

**Issue by MrBokeh** [mostlyserious/riak-js#221]
Hi there, are you going to support riak 2.0?

**Comment by joques** [comment]
Hi all,
I would like to know if riak 2.0 transition is complete. I would like to move the db in my app from riak 1.4 to 2.0. Where can I find the corresponding documentation if the new version is ready
thanks
José

**Comment by Quentin01** [comment]
Hi, Sorry but I am waiting for https://github.com/mostlyserious/riak-js/pull/225 and I don't have enough time at the moment to complete this PR.

**Comment by gigonaut** [comment]
If I can get time to do this later in the week I will, I believe the only reason pr #225 is held up is because of a couple of async issues.

**Comment by Kinetic915** [comment]
Hello all,
Wondering if there is any update on 2.0?
Thanks!

**Comment by Quentin01** [comment]
@Kinetic915 see git@github.com:Quentin01/riak-js.git

**Comment by Quentin01** [comment]
@Kinetic915 See https://github.com/mostlyserious/riak-js/pull/225
