### ISSUE TITLE
Basic connection fails with node v0.10.35 & riak-js 1.0.3

### ISSUE THREAD

**Issue by MarkKropf** [mostlyserious/riak-js#233]
I'm not sure why I can't get even a basic connection to work, I've got riak installed locally, I've also tried it with providing connection options api, host, port.

![image](https://cloud.githubusercontent.com/assets/1703729/5563361/883e0ee0-8e3a-11e4-9afa-a8946664a1fb.png)

![image](https://cloud.githubusercontent.com/assets/1703729/5563368/a98364ba-8e3a-11e4-94b5-a6a27464a486.png)

**Comment by frumioj** [comment]
Update the documentation at http://riak-js.org/ then too (which still shows the old getClient syntax)
