### ISSUE TITLE
No method getClient

### ISSUE THREAD

**Issue by vp4655** [mostlyserious/riak-js#234]
I have problem with first line : require('riak-js').getClient(), it says that for some reason object function has no method getClient and i can't find problem like that anywhere else, please help :)

**Comment by dickeylth** [comment]
I encounted the same problem, how did you fix it?

**Comment by keis** [comment]
after 1.0 getClient is the exported as the module.

so require('riak-js').getClient({...}) becomes require('riak-js')({...})
